name: "Tests automation"
on:
  workflow_dispatch:
jobs:
  tests:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install build Tools
        run: >
          sudo apt-get update
          sudo apt install build-essential -y
      - name: Build module
        run: >
          ./configure --add-module=/path/to/nginx-http-auth-totp
          make
          make install
      
