name: "temp"
on:
  workflow_dispatch:
    inputs:
      nginx-version:
        description: 'nginx version'
        default: "1.29.5"
        required: true
        type: string
jobs:
  tests:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pre-requisites
        run: |
          date
          sudo apt-get update
          sudo apt install build-essential curl python3-pyotp ntpdate -y
          sudo ntpdate -u 0.pool.ntp.org
          date
